"""Shared runtime helpers for the PadelVision analysis pipeline."""

from __future__ import annotations

import logging
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from padelvision.core.ball_tracker import BallTracker
from padelvision.core.detector import PlayerDetector
from padelvision.core.feature_extractor import FeatureExtractor
from padelvision.core.pose_estimator import PoseEstimator
from padelvision.core.preprocessor import VideoPreprocessor
from padelvision.core.scoring_engine import ScoringEngine
from padelvision.core.shot_classifier import ShotClassifier
from padelvision.types import (
    BallTrajectory,
    BoundingBox,
    FrameFeatures,
    ImpactEvent,
    PlayerMetrics,
    PlayerScore,
    PlayerTrack,
    PoseLandmarks,
    Shot,
    VideoMetadata,
)

logger = logging.getLogger(__name__)

ProgressCallback = Callable[[float, str], None]

LANDMARK_SHOULDER_L = 11
LANDMARK_SHOULDER_R = 12


@dataclass
class PipelineConfig:
    """Configuration shared by CLI and API pipeline execution."""

    model_size: str = "s"
    device: str = "auto"
    pose_complexity: str = "full"
    skip_pose: bool = False
    skip_ball: bool = False
    skip_features: bool = False
    skip_classifier: bool = False
    skip_scoring: bool = False
    scoring_config_path: str | Path | None = None
    target_fps: int = 25
    max_dimension: int = 1280
    tracknet_weights: str | Path | None = None


@dataclass
class PipelineArtifacts:
    """Intermediate runtime artifacts generated by the pipeline."""

    metadata: VideoMetadata
    court_roi: BoundingBox | None
    frames: list[np.ndarray] = field(default_factory=list)
    detections_per_frame: list[list] = field(default_factory=list)
    poses_per_frame: list[list[PoseLandmarks]] = field(default_factory=list)
    ball_trajectory: BallTrajectory | None = None
    player_tracks: dict[int, PlayerTrack] = field(default_factory=dict)
    impacts: list[ImpactEvent] = field(default_factory=list)
    player_features: dict[int, list[FrameFeatures]] = field(default_factory=dict)
    player_shots: dict[int, list[Shot]] = field(default_factory=dict)
    player_scores: dict[int, PlayerScore] = field(default_factory=dict)


def run_pipeline_runtime(
    video_path: str | Path,
    config: PipelineConfig,
    progress_cb: ProgressCallback | None = None,
) -> PipelineArtifacts:
    """Run the shared analysis runtime and return intermediate artifacts."""
    video_path = Path(video_path)
    if not video_path.exists():
        raise FileNotFoundError(f"Video file not found: {video_path}")

    report = progress_cb or _default_progress

    preprocessor = VideoPreprocessor(
        target_fps=config.target_fps,
        max_dimension=config.max_dimension,
    )
    pose_estimator: PoseEstimator | None = None
    ball_tracker: BallTracker | None = None

    try:
        report(0.0, "Loading video")
        metadata = preprocessor.load(video_path)
        logger.info(
            "Video: %.1fs | %.1f FPS | %sx%s",
            metadata.duration_sec,
            metadata.fps,
            metadata.width,
            metadata.height,
        )

        court_roi = preprocessor.get_court_roi()

        report(0.05, "Initializing modules")
        detector = PlayerDetector(model_size=config.model_size, device=config.device)
        pose_estimator = None if config.skip_pose else PoseEstimator(model_complexity=config.pose_complexity)

        if not config.skip_ball:
            weights = config.tracknet_weights or "models/tracknet/track.pt"
            ball_tracker = BallTracker(weights_path=weights, device=config.device)

        feature_extractor = None if config.skip_features else FeatureExtractor()
        shot_classifier = None if config.skip_classifier else ShotClassifier(fps=metadata.fps)

        scoring_engine = None
        if not config.skip_scoring:
            scoring_engine = (
                ScoringEngine.from_file(config.scoring_config_path)
                if config.scoring_config_path
                else ScoringEngine()
            )

        report(0.10, "Detecting players and poses")
        frames, detections_per_frame, poses_per_frame = collect_frames_and_detections(
            preprocessor,
            detector,
            pose_estimator,
            court_roi,
        )

        artifacts = PipelineArtifacts(
            metadata=metadata,
            court_roi=court_roi,
            frames=frames,
            detections_per_frame=detections_per_frame,
            poses_per_frame=poses_per_frame,
        )

        report(0.40, "Tracking ball")
        if ball_tracker:
            artifacts.ball_trajectory = ball_tracker.track(
                artifacts.frames,
                fps=metadata.fps,
                court_roi=court_roi,
            )
            detected = sum(
                1
                for pos in artifacts.ball_trajectory.positions
                if pos.is_detected and not pos.interpolated
            )
            logger.info("Ball detected in %s/%s frames", detected, len(artifacts.ball_trajectory.positions))

        report(0.60, "Extracting features")
        if feature_extractor and artifacts.ball_trajectory:
            artifacts.player_tracks = build_player_tracks(artifacts.detections_per_frame, artifacts.poses_per_frame)
            artifacts.impacts = feature_extractor.detect_impacts(
                artifacts.player_tracks,
                artifacts.ball_trajectory,
                metadata.fps,
            )
            artifacts.player_features = extract_features_with_ball_height(
                feature_extractor,
                artifacts.player_tracks,
                artifacts.ball_trajectory,
                (metadata.width, metadata.height),
                court_roi,
                metadata.fps,
            )

        report(0.75, "Classifying shots")
        if shot_classifier and artifacts.ball_trajectory:
            for track_id, features in artifacts.player_features.items():
                impacts_for_player = [impact for impact in artifacts.impacts if impact.player_id == track_id]
                artifacts.player_shots[track_id] = shot_classifier.classify_all(
                    features,
                    impacts_for_player,
                    metadata.fps,
                )

        report(0.90, "Computing scores")
        if scoring_engine and artifacts.ball_trajectory:
            for track_id, features in artifacts.player_features.items():
                shots = artifacts.player_shots.get(track_id, [])
                metrics = compute_player_metrics(shots, features, artifacts.ball_trajectory)
                artifacts.player_scores[track_id] = scoring_engine.compute_score(metrics)

        return artifacts
    finally:
        preprocessor.close()
        if pose_estimator:
            pose_estimator.close()
        if ball_tracker:
            ball_tracker.close()


def collect_frames_and_detections(
    preprocessor: VideoPreprocessor,
    detector: PlayerDetector,
    pose_estimator: PoseEstimator | None,
    court_roi: BoundingBox | None,
) -> tuple[list[np.ndarray], list[list], list[list[PoseLandmarks]]]:
    """Collect frames, detections, and poses in one pass over the video."""
    all_frames: list[np.ndarray] = []
    all_detections: list[list] = []
    all_poses: list[list[PoseLandmarks]] = []

    for batch in preprocessor.frame_batches():
        detections_batch = detector.detect_frames(batch.frames, court_roi=court_roi)
        poses_batch: list[list[PoseLandmarks]] = [[] for _ in batch.frames]

        if pose_estimator:
            poses_batch = pose_estimator.estimate_batch(batch.frames, detections_batch)

        for frame, detections, poses in zip(batch.frames, detections_batch, poses_batch):
            all_frames.append(frame)
            all_detections.append(detections)
            all_poses.append(poses)

    return all_frames, all_detections, all_poses


def build_player_tracks(
    all_detections: list[list],
    all_poses: list[list[PoseLandmarks]],
) -> dict[int, PlayerTrack]:
    """Build player tracks from detection and pose data across all frames."""
    tracks: dict[int, PlayerTrack] = {}

    for frame_idx, (detections, poses) in enumerate(zip(all_detections, all_poses)):
        for detection in detections:
            tid = detection.track_id
            if tid not in tracks:
                tracks[tid] = PlayerTrack(track_id=tid, team=detection.team, detections={}, poses={})
            tracks[tid].detections[frame_idx] = detection

        for pose in poses:
            if pose.player_id is None:
                continue
            if pose.player_id in tracks:
                tracks[pose.player_id].poses[frame_idx] = pose

    PlayerDetector._assign_teams({track_id: list(track.detections.values()) for track_id, track in tracks.items()})
    for track in tracks.values():
        first_detection = next(iter(track.detections.values()), None)
        object.__setattr__(track, "team", first_detection.team if first_detection is not None else track.team)

    return tracks


def extract_features_with_ball_height(
    feature_extractor: FeatureExtractor,
    player_tracks: dict[int, PlayerTrack],
    ball_trajectory: BallTrajectory,
    video_size: tuple[int, int],
    court_roi: BoundingBox | None,
    fps: float,
) -> dict[int, list[FrameFeatures]]:
    """Extract per-player features and enrich them with overhead-ball information."""
    ball_pos_by_frame = {pos.frame_idx: pos for pos in ball_trajectory.positions}
    player_features: dict[int, list[FrameFeatures]] = {}

    for track_id, track in player_tracks.items():
        features = feature_extractor.extract_features(
            track,
            ball_trajectory,
            video_size,
            court_roi,
            fps,
        )

        enhanced: list[FrameFeatures] = []
        for feat in features:
            detection = track.detections.get(feat.frame_idx)
            pose = track.poses.get(feat.frame_idx)
            ball_pos = ball_pos_by_frame.get(feat.frame_idx)
            ball_y = ball_pos.y if ball_pos and ball_pos.is_detected else None
            enhanced.append(
                FrameFeatures(
                    frame_idx=feat.frame_idx,
                    elbow_angle=feat.elbow_angle,
                    shoulder_rotation=feat.shoulder_rotation,
                    hip_rotation=feat.hip_rotation,
                    knee_bend=feat.knee_bend,
                    weight_transfer=feat.weight_transfer,
                    court_position=feat.court_position,
                    player_speed=feat.player_speed,
                    distance_to_ball=feat.distance_to_ball,
                    stroke_phase=feat.stroke_phase,
                    ball_above_head=compute_ball_above_head(detection, pose, ball_y),
                )
            )
        player_features[track_id] = enhanced

    return player_features


def compute_ball_above_head(
    detection,
    pose: PoseLandmarks | None,
    ball_y: float | None,
) -> bool:
    """Check whether the ball is above the player's shoulders."""
    del detection

    if pose is None or ball_y is None or len(pose.keypoints) < LANDMARK_SHOULDER_R + 1:
        return False

    left_shoulder = pose.keypoints[LANDMARK_SHOULDER_L]
    right_shoulder = pose.keypoints[LANDMARK_SHOULDER_R]

    if not (left_shoulder.is_visible and right_shoulder.is_visible):
        return False

    shoulder_y = min(left_shoulder.y, right_shoulder.y)
    return ball_y < shoulder_y


def compute_player_metrics(
    shots: list[Shot],
    features: list[FrameFeatures],
    ball_trajectory: BallTrajectory,
) -> PlayerMetrics:
    """Compute aggregated metrics for a player from features and shots."""
    return ScoringEngine().compute_metrics_from_data(
        shots=shots,
        avg_elbow_angle=_compute_average_elbow_angle(features),
        avg_speed_ms=_compute_average_speed(features),
        avg_ball_speed_kmh=_compute_avg_ball_speed(ball_trajectory),
        avg_position_optimality=_compute_position_optimality(features),
        court_coverage_pct=_compute_court_coverage(features),
    )


def _compute_average_elbow_angle(features: list[FrameFeatures]) -> float:
    angles = [feature.elbow_angle for feature in features if feature.elbow_angle is not None]
    return sum(angles) / len(angles) if angles else 0.0


def _compute_average_speed(features: list[FrameFeatures]) -> float:
    speeds = [feature.player_speed for feature in features if feature.player_speed is not None]
    if not speeds:
        return 0.0
    return (sum(speeds) / len(speeds)) / 100.0


def _compute_avg_ball_speed(ball_trajectory: BallTrajectory) -> float:
    speeds = [speed for speed in ball_trajectory.speed_kmh if speed > 0]
    return sum(speeds) / len(speeds) if speeds else 0.0


def _compute_position_optimality(features: list[FrameFeatures]) -> float:
    positions = [feature.court_position for feature in features if feature.court_position is not None]
    if not positions:
        return 0.0

    optimal_center = (0.5, 0.5)
    distances = []
    for x_pos, y_pos in positions:
        dist = ((x_pos - optimal_center[0]) ** 2 + (y_pos - optimal_center[1]) ** 2) ** 0.5
        max_dist = (0.5**2 + 0.5**2) ** 0.5
        distances.append(1.0 - dist / max_dist)

    return sum(distances) / len(distances)


def _compute_court_coverage(features: list[FrameFeatures], grid_size: int = 4) -> float:
    positions = [feature.court_position for feature in features if feature.court_position is not None]
    if not positions:
        return 0.0

    visited: set[tuple[int, int]] = set()
    for x_pos, y_pos in positions:
        visited.add((min(int(x_pos * grid_size), grid_size - 1), min(int(y_pos * grid_size), grid_size - 1)))

    return len(visited) / (grid_size * grid_size)


def _default_progress(progress: float, message: str) -> None:
    logger.info("[%s%%] %s", int(progress * 100), message)
